### ISSUE TITLE
Add logger support

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/kan#5]

**Comment by valikos** [comment]
@davydovanton do you have any ideas how logger should work and which kind of activity to log?

**Comment by davydovanton** [comment]
I think it will be cool to just allow `logger` getter in ability blocks. Something like:

```ruby
class Post::Abilities
  include Kan::Abilities

  register 'read' do |user, _|
    logger # => logger instance
    logger.info 'Something happened'
    true
  end
end
```

And initialization:

```ruby
admin_abilities = Kan::Application.new(
  posts: Post::AdminAbilities.new(logger: MyLoggerClass.new),
  comments: Comment::AdminAbilities.new, # => will use default STDOUT logger instance
)
```

**Comment by valikos** [comment]
@davydovanton could you please check https://github.com/davydovanton/kan/pull/7?
Is this correct for you?
I think there will be good to have some global Kan::Application::Logger that can be configured by configuration. What do you think about this?
