### ISSUE TITLE
Syntax errors in the readme

### ISSUE THREAD

**Issue by elia** [davydovanton/kan#9]
Was looking at the README and seems that all the inline blocks are missing parens around the arguments, e.g.:

```
  register 'read' { |_, _| true }
```

should be:

```
  register('read') { |_, _| true }
```

**Comment by davydovanton** [comment]
Hey, awesome catch!
Could you make PR for this? 💗

**Comment by wizardone** [comment]
@elia If you can't do it I am happy to fix those, since it is a small change.

**Comment by berniechiu** [comment]
Help added https://github.com/davydovanton/kan/pull/14

**Comment by davydovanton** [comment]
Thanks for you help, folks! <3
